berulds/eventseeker

Gemfile
Gemfile.lock
README.md
app/controllers/application_controller.rb
app/policies/application_policy.rb

Added pundit gem, you will have to do a bundle install
Added lines of basics action with pundit on the README, refers to the lecture linked if you have any questions on how to do it
WHENEVER you add/modifiy a crud actions, make sure to add the logic with pundit aswell.

Please read README.md

---

.gitignore
Gemfile
Gemfile.lock
config/environments/development.rb
config/environments/production.rb
config/storage.yml
db/migrate/20231110024623_create_active_storage_tables.active_storage.rb
db/schema.rb

Heyhey. Added the Cloudinary gem and changed storage options to Cloudinary.
Set up active storage along with Cloudinary.

added cloudinary to app and heroku

---

.gitignore
app/controllers/application_controller.rb
app/models/user.rb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
db/migrate/20231110032601_add_user_name_to_users.rb
db/schema.rb

Please do a rails db:migrate to update your user table

 added username column for users, updated signinp/edit forms

---

README.md
app/controllers/itineraries_controller.rb
app/models/itinerary.rb
app/policies/itinerary_policy.rb
app/views/itineraries/new.html.erb
config/routes.rb
db/migrate/20231110054824_create_itineraries.rb
db/schema.rb
test/controllers/itineraries_controller_test.rb
test/models/itinerary_test.rb
test/policies/itinerary_policy_test.rb

Generated controller/model and policy  for itineraries.
refers to readme if needed

 added itinerary controller and model, used pundit

---

app/controllers/events_controller.rb
app/models/event.rb
app/policies/event_policy.rb
app/views/events/new.html.erb
config/routes.rb
db/migrate/20231110054926_create_events.rb
db/schema.rb
test/controllers/events_controller_test.rb
test/models/event_test.rb
test/policies/event_policy_test.rb

Generated events model and controller along with pundit.

generated event model, controller, and pundit

---

app/controllers/event_genres_controller.rb
app/models/event_genre.rb
app/policies/event_genre_policy.rb
db/migrate/20231110234922_create_event_genres.rb
db/schema.rb
test/controllers/event_genres_controller_test.rb
test/models/event_genre_test.rb
test/policies/event_genre_policy_test.rb

Hey guys. Generated event_genre model and controller, set it up with pundit.
Remember to migrate on your next pull.

generated event_genre model controller pundit

---

README.md
db/migrate/20231111001948_add_name_to_itineraries.rb
db/schema.rb

Just created migration to add name to itineraries.
updated readme for second step so basic logic to authorize

added name to itineraries and updated readme

---

app/controllers/events_controller.rb
app/policies/event_policy.rb
app/views/events/edit.html.erb
config/routes.rb
db/schema.rb

Built destroy and update methods for events. Testing, both working.
Sadly no screenshots for this one.

created destroy and update methods, testing both working

---

app/helpers/services.rb
db/schema.rb

Began looking at APIs'. We have a plan. We're a class to call the API.

added api services class

---

Gemfile
Gemfile.lock
app/controllers/pages_controller.rb
app/models/event.rb
app/models/genre.rb
app/models/user.rb
app/models/user_genre.rb
app/views/pages/home.html.erb
config/environments/development.rb
db/schema.rb
db/seeds.rb

Added user and event photos to cloudinary. Updated seed file so it now adds user photos during user creation, and event photos during event creation.
Changed development storage back to cloudinary.
Added code on view/pages/home to show all photos. All photos should show prior to logging in.
Please bundle install as there are new gems.
Please rails db:seed to ensure working on your local.
Be patient running seed. Takes a touch longer to run with all the photos.

added photos to cloudinary and seed file

---

Gemfile

added open uri gem as heroku push was asking for it

---

.gitignore
Gemfile.lock
app/controllers/pages_controller.rb
app/services/api_service.rb
app/views/pages/home.html.erb
config/routes.rb

Hey guys,
Created a file in a folder called services containing the api call that is called in the pages controller 'events_result" action. The search form and search results container is within the home.html.erb file. The results are only displaying as a list so far as we can work on the display furthermore down the road.

Set up api call in api_service.rb and added search and results to home.html.erb

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_dashboard.scss
app/controllers/application_controller.rb
app/controllers/events_controller.rb
app/controllers/pages_controller.rb
app/javascript/controllers/datepicker_controller.js
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/events/edit.html.erb
app/views/events/index.html.erb
app/views/events/new.html.erb
app/views/events/show.html.erb
app/views/itineraries/edit.html.erb
app/views/itineraries/new.html.erb
app/views/itineraries/show.html.erb
app/views/layouts/application.html.erb
app/views/pages/about_us.html.erb
app/views/pages/dashboard.html.erb
app/views/pages/home.html.erb
app/views/shared/_footer.html.erb
app/views/shared/_navbar.html.erb
config/importmap.rb
config/routes.rb

Hey all. 
A dashboard page has been added - along with links to working pages.
The footer has been added - links have been added to the navbar & footer.
Div containers added to most pages to centre content.
An about us page has been added.
Updated design/layout, more wireframe visuals at the moment using predominately bootstrap.
Flatpickr js controller generated and all forms with dates amended to select dates from calendar rather than typing in.

Building dashboard linking all pages

---

app/controllers/application_controller.rb
app/controllers/bookmarks_controller.rb
app/controllers/event_genres_controller.rb
app/controllers/events_controller.rb
app/controllers/itineraries_controller.rb
app/controllers/itinerary_events_controller.rb
app/policies/application_policy.rb
app/policies/bookmark_policy.rb
app/policies/event_genre_policy.rb
app/policies/event_policy.rb
app/policies/itinerary_event_policy.rb
app/policies/itinerary_policy.rb
test/policies/bookmark_policy_test.rb
test/policies/event_genre_policy_test.rb
test/policies/event_policy_test.rb
test/policies/itinerary_policy_test.rb

Commented out all pundit's logic/scope interaction in eventseeker.
changed the @events on dashboard/events to still display all events

Removed pundit... for now

---

app/controllers/bookmarks_controller.rb
app/controllers/pages_controller.rb
app/models/event.rb
app/views/bookmarks/index.html.erb
app/views/events/index.html.erb
app/views/layouts/application.html.erb
app/views/pages/dashboard.html.erb
config/routes.rb

Added create and destroy action for bookmark

---

app/controllers/pages_controller.rb
app/services/api_service.rb
app/views/pages/home.html.erb
quit

Added search filtering for date and location. Date is hard coded in to be within Australia, I'll be working on fixing that next merge. Date also displays some additional dates if selected dates don't have 10 or more events, will address this also next merge.

added search filtering for location and date

---

app/controllers/bookmarks_controller.rb
app/views/bookmarks/index.html.erb
app/views/events/index.html.erb
config/routes.rb
db/migrate/20231118010039_change_bookmarks_logic.rb
db/schema.rb
db/seeds.rb

Please run db:drop create migrate and seed as i changed the columns in bookmark
fixed everything for bookmarks and added some logics in cards

changed and fix all cruds action for bookmarks

---

app/controllers/events_controller.rb
app/controllers/itinerary_events_controller.rb
app/views/events/index.html.erb
app/views/itineraries/show.html.erb
app/views/itinerary_events/new.html.erb
config/routes.rb

Fixed add event to itinerary issue. Can now add an event to an itinerary and delete from itinerary.

Fixing itinerary events

---

.byebug_history
Gemfile
Gemfile.lock
app/assets/stylesheets/pages/_home.scss
app/controllers/pages_controller.rb
app/javascript/controllers/location_autocomplete_controller.js
app/javascript/controllers/map_controller.js
app/services/api_service.rb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/shared/_events_map_window.html.erb
config/importmap.rb
config/initializers/geocoder.rb

Hey guys here is the long awaited alex push!!! 
okay so I've updated the search inputs to take the users query(sports for example), date(using datepicker) and location which uses geoapify autocomplete api to show a drop down list of suggestions as the user types to handle any location errors provided by the initial google events api. The styling is very minimal as I wanted to push and pull the lastest version before continuing. Some small changes will have to be made so if you find any, leave comments or suggestions and i'll make the changes before merging. 
Mapbox was installed and initialized however there were some accuracy problems displaying the markers on a map with the coordinates so we will have to decide if it is an importa`nrt feature to get done by saturday.

Updated home page api search call

---

app/controllers/pages_controller.rb
app/services/api_service.rb
app/views/pages/home.html.erb

Removed where search input from home, api call and search event method logic.

Removed Where search from landing page

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/pages/_about_us.scss
app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_index.scss
app/controllers/pages_controller.rb
app/services/api_service.rb
app/views/pages/about_us.html.erb
app/views/pages/home.html.erb
config/routes.rb

Added a 'see more results' button which allows the user to see the next 10 results each time they hit it.
I slightly adjusted the event card to limit the description length. added purchase ticket button which opens modal (not working yet - same issue passing info into a modal 😡)
Added LinkedIn and GitHub buttons to About Us page

Search pagination purchase modal

---

app/controllers/events_controller.rb
app/views/events/index.html.erb
app/views/pages/home.html.erb

Added purchase button, modal opens with links to other sites to purchase tix from.
See more events button now only shows if there are more than 10 results.
Purchase button still not working in our saved events, I'll need to update seed file to update every event we have so that the ticket info contains the right info we need.

Purchase modal

---

app/controllers/bookmarks_controller.rb
app/controllers/pages_controller.rb
app/views/pages/dashboard.html.erb

add tab for dashboard

---

app/views/pages/home.html.erb

Now back to 3 columns on home page layout

fixed home page layout, now back to 3 columns

---

app/assets/stylesheets/pages/_home.scss
app/views/itineraries/index.html.erb
app/views/pages/dashboard.html.erb
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb

changed background, some paths and logics

---

Gemfile
config/cable.yml

 added redis and redis line in config.yml

---

app/controllers/events_controller.rb
app/controllers/pages_controller.rb
app/javascript/controllers/search_controller.js
app/views/itineraries/show.html.erb
app/views/pages/dashboard.html.erb
app/views/pages/home.html.erb

Purchase button now works on all cards where applicable. Currently opens a modal as below. Will adapt with FE.
Also added event cards to itinerary page.

finalised purchase modal

---

app/views/pages/dashboard.html.erb

Created the top section of the dashboard. Pending: The stats / cleaning it up (will do this later)

Dashboard top section

---

app/assets/stylesheets/pages/_home.scss
app/views/chatrooms/show.html.erb
app/views/pages/dashboard.html.erb
app/views/pages/home.html.erb

Fixed footer issue on dashboard and chatrooms. Re-aligned code.

fixed footer across dashboard and chatrooms. also adjusted code layout

---

app/assets/stylesheets/components/_chatroom.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_message.scss
app/controllers/bookmarks_controller.rb
app/controllers/chatrooms_controller.rb
app/controllers/events_controller.rb
app/controllers/messages_controller.rb
app/javascript/controllers/chatroom_subscription_controller.js
app/javascript/controllers/tab_controller.js
app/models/message.rb
app/views/chatrooms/show.html.erb
app/views/events/index.html.erb
app/views/pages/dashboard.html.erb
app/views/shared/_chatrooms.html.erb
app/views/shared/_navbar.html.erb

Started on chatroom layout. 
There are issues with our redirects/link_to's with all-events and chatrooms as they require ID passed through params we may not be able to get working within a tab. I'll suss tomorrow. App will work, just some links won't take you to where youd expect.

added layout to chatrooms

---

app/controllers/bookmarks_controller.rb
app/controllers/events_controller.rb
app/views/pages/dashboard.html.erb
app/views/shared/_my_events.html.erb
app/views/shared/_navbar.html.erb

Removed all events and chatrooms from tab list on dashboard page.
Added all events button onto my events tab page.
Add chatroom link on event card to chatrooms page.
Updated navbar drop down list.

Changed tab list

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_chatroom.scss
app/assets/stylesheets/components/_forms.scss
app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/pages/_home.scss
app/controllers/messages_controller.rb
app/models/itinerary.rb
app/views/chatrooms/show.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/itineraries/new.html.erb
app/views/pages/dashboard.html.erb
app/views/pages/home.html.erb
app/views/shared/_all_events.html.erb
app/views/shared/_navbar.html.erb
config/application.rb

All forms are now simple and consistent, added edit user form/link to dashboard drop down menu.
Fixed time in chat messages showing as London time. Now in Aus time zone.
Updated search date and submit buttons.
Fixed home page background image.
Changed static red/yellow background image across all other pages to dynamic/wave.

completed forms css, multiple small changes

---

app/assets/stylesheets/components/_index.scss

fixed ; on line 8 of css

---

app/views/shared/_all_events.html.erb

Added event modal, when you click on an event name from the homepage. Also, added the bookmark me button within it, still need to add the purchase button in a new PR after.

added event modal with bookmark me button

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/itineraries/_show.scss
app/assets/stylesheets/pages/_dashboard.scss
app/assets/stylesheets/pages/_home.scss
app/views/itineraries/show.html.erb
app/views/shared/_itineraries.html.erb

Hey, 
I've styled the itinerary tab cards according to figma design. Will have to decide on some fonts and button designs to ensure consistency and ease of application. Added a display to cards to see how many events an itinerary has.

Styled Itinerary tab cards

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_chatroom.scss
app/assets/stylesheets/itineraries/_show.scss
app/assets/stylesheets/pages/_home.scss
app/views/chatrooms/show.html.erb
app/views/events/index.html.erb
app/views/shared/_all_events.html.erb
app/views/shared/_my_events.html.erb

Adjusted event cards and chatroom event cards scss to incorporate interested users icons.

fixed scss on event cards to incorporate interested user icons

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_chatroom.scss
app/assets/stylesheets/components/_modal.scss
app/assets/stylesheets/config/_fonts.scss
app/assets/stylesheets/itineraries/_show.scss
app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_index.scss
app/controllers/events_controller.rb
app/controllers/pages_controller.rb
app/views/chatrooms/show.html.erb
app/views/events/index.html.erb
app/views/itineraries/show.html.erb
app/views/pages/home.html.erb
app/views/shared/_all_events.html.erb
app/views/shared/_itineraries.html.erb
app/views/shared/_my_events.html.erb

Added chat icon to all cards where event is bookmarked by user and chatroom exists. 
Added interested users icons to other cards. Slightly adjusted wording from users to seekers.
Added and changed over fonts.
Fixed vertical ellipsis icon on event itinerary show page.

added chat icon/link to call cards

---

app/assets/stylesheets/components/_alert.scss
app/controllers/bookmarks_controller.rb
app/controllers/events_controller.rb
app/views/events/index.html.erb
app/views/pages/home.html.erb

fixed create from api not saving bookmark for every user
changed text for modal
fixed flashes position on the screen

thursday fixes

---

app/controllers/pages_controller.rb
app/views/shared/_overview.html.erb

refined the overview tab of the dashboard
